### ISSUE TITLE
JOSM properties

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#20]
- [x] symbol- (#34)
- [x] text-anchor-vertical,  text-anchor-horizontal (#38)
- [x] dashes-offset, dashes-background-color (#35)
- [x] miterlimit (764621f98d9f5d1631c46af5ae74744f60eb1d6c)
- [x] repeat-image- (#47)
- [x] left-casing-, right-casing- (#48)
