### ISSUE TITLE
Delay loading of geometry/meta data

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#99]
When not needing geometry/meta data (e.g. when doing relationship queries), do not load geometry/meta data. Add function which loads geometry/meta data later, when requested.

**Comment by plepe** [comment]
- [ ] (eval) functions which need geometry need to check if geometry is loaded
- [ ] check for geometry needs to be done before eval function is called
- [ ] update DB-functions, so that geometry does not get loaded per default (not for main `objects_bbox()` though)
- [ ] add function (or modify `objects_by_id()`) function to download geo et.al.
- [ ] update documentation
